name: Build .NET Console and Upload ZIP Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x   # adjust if needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish API
        run: >
          dotnet publish
          action_try.csproj
          -c Release
          -o publish

      - name: Create ZIP package
        run: |
          Compress-Archive -Path publish\* -DestinationPath compiled.zip

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: conole-zip
          path: console-build.zip
